INSERT INTO PERMISSION (PERMISSION_ID, PERMISSION_NAME) VALUE (1, 'LIST_USERS');
INSERT INTO PERMISSION (PERMISSION_ID, PERMISSION_NAME) VALUE (2, 'CREATE_USERS');
INSERT INTO PERMISSION (PERMISSION_ID, PERMISSION_NAME) VALUE (3, 'DELETE_USERS');
INSERT INTO PERMISSION (PERMISSION_ID, PERMISSION_NAME) VALUE (4, 'EDIT_USERS');

INSERT INTO ROLE (ROLE_ID, ROLE_NAME) VALUE (1, 'ADMIN_ROLE');

INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID) VALUE (1,1);
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID) VALUE (1,2);
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID) VALUE (1,3);
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID) VALUE (1,4);

INSERT INTO USER (USER_ID, USERNAME, PASSWORD, ROLE_ID) VALUE (1, 'admin', '$2a$10$2y1b/MSGK9Zvpdrb4hzpwO5EseOb8db.GGQkLZd5pjvzMq/YeeI9.', 1);